### ISSUE TITLE
Green bubble display issue

### ISSUE THREAD

**Issue by NouFuS** [Unity-Technologies/BanditDungeon#2]
Due to state_values getting negative when evaluating low reward actions (happens a lot in 'easy' mode), the green bubbles get negative scaling, breaking their meaning.
![Scale bug](https://user-images.githubusercontent.com/11455889/74085886-ff21e400-4a7d-11ea-9e1d-f5576d69f6dd.png)

**Comment by NouFuS** [comment]
Easy fix is to clip scaling value to prevent negative. Is is possible to send pull request, or is it managed only by Unity devs?

**Comment by awjuliani** [comment]
Hi @NouFuS 

Please feel free to send a PR.
